name: "PlaytimeStats"
main: "io.github.arcaneplugins.playtimestats.plugin.bukkit.PlaytimeStats"
version: "${version}"
description: "${description}"
authors: [ "lokka30" ]
website: "https://github.com/ArcanePlugins/PlaytimeStats/"
api-version: "1.13"
softdepend:
  - "PlaceholderAPI"
  - "EssentialsX"
libraries:
  - "com.h2database:h2:${h2Version}"
permissions:
  playtimestats.command.playtime:
    default: true
    description: "allows you to run `/playtime`"
  playtimestats.command.playtimestats:
    default: true
    description: "allows you to run `/playtimestats` (base command)"
  playtimestats.command.playtimestats.reload:
    default: op
    description: "allows you to run `/playtimestats reload`"
  playtimestats.command.playtimestats.version:
    default: true
    description: "allows you to run `/playtimestats version`"
