name: "PlaytimeStats"
main: "io.github.arcaneplugins.playtimestats.plugin.bukkit.PlaytimeStats"
version: "${version}"
description: "${description}"
authors: [ "lokka30" ]
website: "https://github.com/arcaneplugins/playtimestats/"
api-version: "1.13"
softdepend:
  - "PlaceholderAPI"
